default:
    tags:
      - shared

variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build

build:
    stage: build
    script:
        - docker build -t ddns-server:latest .

    only:
        - main
